#!/bin/sh

[ $TERM = "xterm-kitty" ] && kitty +kitten icat --clear --stdin no --silent --transfer-mode file < /dev/null > /dev/tty

[ -n "$FIFO_UEBERZUG" ] && printf '{"action": "remove", "identifier": "PREVIEW"}\n' > "$FIFO_UEBERZUG"
