#!/bin/sh

[ -n "$UB_SOCKET" ] && ueberzug cmd -s "$UB_SOCKET" -a remove -i PREVIEW

[ "$TERM" = "xterm-kitty" ] && exec kitten icat --clear --stdin no --transfer-mode memory </dev/null >/dev/tty
[ "$TERM" = "xterm-ghostty" ] && exec kitten icat --clear --stdin no --transfer-mode memory </dev/null >/dev/tty

[ -n "$FIFO_UEBERZUG" ] && printf '{"action": "remove", "identifier": "PREVIEW"}\n' > "$FIFO_UEBERZUG"

