#!/bin/sh
# shellcheck disable=SC2015,SC2046
# Preview script built for use with lf and fzf
# Based on Luke Smith's scripts https://github.com/LukeSmithxyz/voidrice

# Same script, but without images:
# $XDG_CONFIG_HOME/lf/previewer_noimages

# $1 - file path
# $2 - terminal width
# $3 - terminal height
# $4 - x
# $5 - y

# Dependencies:
# images    - kitty terminal(works out of the box, ssh requires tweaking(mb not anymore)) or ueberzugpp (X11 or hyprland/sway) or chafa (symbols/sixel preview, work over ssh out of the box)
# svg images- imagemagick
# videos	- same as images + ffmpegthumbnailer
# pdf		- poppler
# archives  - tar for .tar.*, unzip for .zip, unrar for .rar
# iso		- libcdio
# html		- lynx (used by default), can be replaced with w3m or links

mediainfo() {
	command mediainfo "$1" | sed '/Complete name/ s/\/.*\///; s/Complete name/Name/; s/\s*:/: \\/' | column -tL -s "\\"
}

image() {
	if [ "$TERM" = "xterm-kitty" ] || [ "$TERM" = "xterm-ghostty" ]; then
		kitty +kitten icat --silent --stdin no --transfer-mode file --place "${2}x$(($3 - 1))@${4}x${5}" "$1" </dev/null >/dev/tty
	elif [ -f "$1" ] && [ -n "$UB_SOCKET" ]; then
		ueberzug cmd -s "$UB_SOCKET" -a add -i PREVIEW -x "$4" -y "$5" --max-width "$(($2 - 1))" --max-height "$3" -f "$1"
	elif [ $(which chafa 2>/dev/null) ]; then
		chafa -s "$2x$3" --animate off --polite on "$1" || mediainfo "$6" # Auto
		# chafa "$1" -f symbols -s "$(($2-3))x$(($3-2))" --animate false || mediainfo "$6" # Symbols
		# chafa -f sixel -s "$2x$3" --animate off --polite on "$1" || mediainfo "$6" # Sixel
		# Chafa can also be used with sixel-supported terminals (e.g. foot)
	else
		mediainfo "$6"
	fi
	exit 1
}

listarchive() {
	case "$(basename "$1" | tr '[:upper:]' '[:lower:]')" in
		*.zip) zipinfo -1 "$1" | stick "$1" ;;
		*.jar) zipinfo -1 "$1" | stick "$1" ;;
		*.tar.gz) tar -ztf "$1" | stick "$1" ;;
		*.tar.bz2) tar -jtf "$1" | stick "$1" ;;
		*.tar.xz) tar -Jtf "$1" | stick "$1" ;;
		*.tar.zst) tar --zstd -tf "$1" | stick "$1" ;;
		*.tar) tar -tf "$1" | stick "$1" ;;
		*.rar) unrar lb "$1" | stick "$1" ;;
		*.7z) printf "# Preview is disabled due to an error \n# with password protected archives" ;; #7z l "$1"
	esac
}

stick() {
	if [ $(command -v tree) ]; then
		basename "$1"
		tree -C --fromfile | tail -n+2
	else
		cat
	fi
}

glowingrat() {
	if [ $(which glow) ] && { [ "${1##*.}" = "md" ] || [ "${1##*.}" = "MD" ]; }; then
		CLICOLOR_FORCE=1 glow -w "$(($2 - 6))" -s dark "$1"
		exit 0
	elif [ $(which bat) ]; then
		bat -fn --terminal-width "$(($2 - 6))" "$1"
	elif [ $(which batcat) ]; then
		batcat -fn --terminal-width "$(($2 - 6))" "$1"
	else
		cat "$1"
	fi
}

# file -Lb --mime-type -- "$1"
case "$(file -Lb --mime-type -- "$1")" in
	image/avif)
		CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/lf/thumb.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | cut -d' ' -f1)"
		[ ! -f "$CACHE" ] && convert "$1" "$CACHE.jpg"
		image "$CACHE.jpg" "$2" "$3" "$4" "$5" "$1"
		;;
	image/vnd.djvu)
		CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/lf/thumb.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | cut -d' ' -f1)"
		[ ! -f "$CACHE" ] && djvused "$1" -e 'select 1; save-page-with /dev/stdout' | convert -density 200 - "$CACHE.jpg" >/dev/null 2>&1
		image "$CACHE.jpg" "$2" "$3" "$4" "$5" "$1"
		;;
	image/svg+xml)
		if [ "$UB_SOCKET" ]; then
			CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/lf/thumb.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | cut -d' ' -f1)"
			[ ! -f "$CACHE" ] && convert "$1" "$CACHE.jpg"
			image "$CACHE.jpg" "$2" "$3" "$4" "$5" "$1"
		else
			image "$1" "$2" "$3" "$4" "$5" "$1"
		fi
		;;
	image/*) image "$1" "$2" "$3" "$4" "$5" "$1" ;;
	text/html) [ $(which lynx 2>/dev/null) ] && lynx -width="$4" -display_charset=utf-8 -dump "$1" || glowingrat "$1" "$4" ;;
	text/troff) man ./ "$1" | col -b ;;
	text/* | */xml | application/json | application/x-ndjson | application/javascript | application/x-wine-extension-ini) glowingrat "$1" "$4" ;;
	audio/* | application/octet-stream | video/3gpp) mediainfo "$1" ;;
	video/*)
		if [ $(which ffmpegthumbnailer) ] && { [ "$UB_SOCKET" ] || [ "$TERM" = "xterm-kitty" ] || [ $(which chafa 2>/dev/null) ]; }; then
			CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/lf/thumb.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | cut -d' ' -f1)"
			[ ! -f "$CACHE" ] && ffmpegthumbnailer -i "$1" -o "$CACHE" -s 0 -q 4
			image "$CACHE" "$2" "$3" "$4" "$5" "$1"
		else
			mediainfo "$1"
		fi
		;;
	*/pdf)
		if [ $(which pdftoppm) ] && { [ "$UB_SOCKET" ] || [ "$TERM" = "xterm-kitty" ] || [ $(which chafa 2>/dev/null) ]; }; then
			CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/lf/thumb.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | cut -d' ' -f1)"
			[ ! -f "$CACHE.jpg" ] && pdftoppm -jpeg -f 1 -singlefile "$1" "$CACHE"
			image "$CACHE.jpg" "$2" "$3" "$4" "$5" "$1"
		else
			pdftotext "$1" -
		fi
		;;
	*/epub+zip | */mobi*)
		if [ $(which gnome-epub-thumbnailer) ] && { [ "$UB_SOCKET" ] || [ "$TERM" = "xterm-kitty" ] || [ $(which chafa 2>/dev/null) ]; }; then
			CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/lf/thumb.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | cut -d' ' -f1)"
			[ ! -f "$CACHE.jpg" ] && gnome-epub-thumbnailer "$1" "$CACHE.jpg"
			image "$CACHE.jpg" "$2" "$3" "$4" "$5" "$1"
		else
			mediainfo "$1"
		fi
		;;
	application/*zip | application/*7z* | application/x-rar | application/x-bzip2 | application/x-xz | application/zstd | application/vnd.rar) listarchive "$1" ;;
	application/x-iso9660-image) iso-info -l --no-header "$1" ;;
	*opendocument*) [ $(which odt2txt 2>/dev/null) ] && odt2txt "$1" || echo "odt2txt not installed" ;;
	application/vnd.openxmlformats-officedocument.wordprocessingml.document) [ $(which docx2txt 2>/dev/null) ] && docx2txt "$1" - || echo "docx2txt not installed" ;;
	application/pgp-encrypted) gpg -d -- "$1" ;;
	application/vnd.sqlite3) sqlist "$1" ;;
	application/x-pie-executable | application/x-executable | application/vnd.microsoft.portable-executable | application/x-sharedlib | application/x-mach-binary)
		file -L "$1" | cut -d: -f2- | tr ',' '\n' | sed 's/^[[:space:]]*//'
		if readelf -d "$1" 2>/dev/null | grep NEEDED >/dev/null; then
			echo
			echo "Dependencies:"
			readelf -d "$1" | grep NEEDED | sed 's/.*Shared library: \[\(.*\)\]/\1/'
		fi
		;;
	font/sfnt | font/ttf | application/vnd.ms-opentype) fc-scan -b "$1" ;;
	inode/x-empty) ;;
	*) printf "Unsupported mime-type: " && file -Lb --mime-type -- "$1" ;;
esac

#exit 1 # uncomment to disable preview caching
