#!/bin/sh
# Preview script built for use with lf and fzf
# Based on Luke Smith's scripts https://github.com/LukeSmithxyz/voidrice

# Same script, but with images:
# $XDG_CONFIG_HOME/lf/previewer

# $1 - file path
# $2 - terminal width
# $3 - terminal height
# $4 - x
# $5 - y

# Dependencies:
# pdf		- poppler
# archives  - tar for .tar.*, unzip for .zip, unrar for .rar
# iso		- libcdio
# html		- lynx (used by default), can be replaced with w3m or links

listarchive(){
	case "$(basename "$1" | tr '[A-Z]' '[a-z]')" in
		*.zip) zipinfo "$1" | tail -n+2 ;; # unzip -l can be used instead for different output
		*.jar) zipinfo "$1" | tail -n+2 ;;
		*.tar.gz) tar -ztvf "$1" ;;
		*.tar.bz2) tar -jtvf "$1" ;;
		*.tar.xz) tar -Jtvf "$1" ;;
		*.tar.zst) tar --zstd -tvf "$1";;
		*.tar) tar -tvf "$1" ;;
		*.rar) unrar l "$1" | tail -n+7 | head -n -2 ;;
		*.7z) printf "# Preview is disabled due to an error \n# with password protected archives" ;; #7z l "$1"
	esac
}

glowingrat(){
	if [ $(which glow) ] && { [ "${1##*.}" = "md" ] || [ "${1##*.}" = "MD" ]; }; then
		glow -s dark "$1"
		exit 0
	elif [ $(which bat) ]; then
		bat -fn --terminal-width "$(($2-6))" "$1"
	elif [ $(which batcat) ]; then
		batcat -fn --terminal-width "$(($2-6))" "$1"
	else
		cat "$1"
	fi
}

case "$(file -Lb --mime-type -- "$1")" in
	image/*) mediainfo "$1" | sed '/Complete name/ s/\/.*\///; s/Complete name/Name/; s/\s*:/: \\/' | column -tL -s "\\" && exit 1;;
	text/html) [ $(which lynx 2>/dev/null) ] && lynx -width="$4" -display_charset=utf-8 -dump "$1" || glowingrat "$1" "$4" ;;
	text/troff) man ./ "$1" | col -b ;;
	text/* | */xml | application/json | application/x-ndjson) glowingrat "$1" "$4";;
	audio/* | application/octet-stream) mediainfo "$1" | sed '/Complete name/ s/\/.*\///; s/Complete name/Name/; s/\s*:/: \\/' | column -tL -s "\\" ;;
	video/* ) mediainfo "$1" | sed '/Complete name/ s/\/.*\///; s/Complete name/Name/; s/\s*:/: \\/' | column -tL -s "\\" && exit 1 ;;
	*/pdf) pdftotext "$1" - ;;
	*/epub+zip|*/mobi*) mediainfo "$1" | sed '/Complete name/ s/\/.*\///; s/Complete name/Name/; s/\s*:/: \\/' | column -tL -s "\\" ;;
	application/*zip | application/*7z* | application/x-rar | application/x-bzip2 | application/x-xz) listarchive "$1" ;;
	application/x-iso9660-image) iso-info -l --no-header "$1" ;;
	*opendocument*) odt2txt "$1" ;;
	application/pgp-encrypted) gpg -d -- "$1" ;;
	inode/x-empty) ;;
	*) printf "Unsupported mime-type: " && file -Lb --mime-type -- "$1" ;;
esac

#exit 1 # uncomment to disable preview caching
