#!/bin/sh

# add ~/.local/bin and folders in it to PATH
export PATH="$PATH:$(find ~/.local/bin -type d | paste -sd ':' -)"

# Default programs
export TERMINAL="alacritty"
if [ -x "$(command -v nvim)" ]; then
  export EDITOR="nvim" 
  export VISUAL="nvim" 
  export MANPAGER='nvim +Man!'
  alias vimdiff="nvim -d"
else
  export EDITOR="vim"
  export VISUAL="vim"
fi


#export BROWSER="firefox"

# use dolphin as a file picker on kde plasma
[ "$XDG_CURRENT_DESKTOP" = "KDE" ] && export GTK_USE_PORTAL=1

# ~/ cleanup
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"

export ANDROID_HOME="$XDG_DATA_HOME/android"
export ANDROID_SDK_ROOT="$XDG_DATA_HOME/android"
export ANDROID_SDK_HOME="$XDG_DATA_HOME/android"
export ANDROID_USER_HOME="$XDG_DATA_HOME/android"
export ANSIBLE_CONFIG="$XDG_CONFIG_HOME/ansible/ansible.cfg"
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export CUDA_CACHE_PATH="$XDG_CACHE_HOME/nv"
export DOCKER_CONFIG="$XDG_CONFIG_HOME/docker"
export FFMPEG_DATADIR="$XDG_CONFIG_HOME/ffmpeg"
export GOMODCACHE="$XDG_CACHE_HOME/go/mod"
export GOPATH="$XDG_DATA_HOME/go"
export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc-2.0"
export GVIMINIT='let $MYGVIMRC = !has("nvim") ? "$XDG_CONFIG_HOME/vim/gvimrc" : "$XDG_CONFIG_HOME/nvim/init.gvim" | so $MYGVIMRC'
export VIMINIT='let $MYVIMRC = !has("nvim") ? "$XDG_CONFIG_HOME/vim/vimrc" : "$XDG_CONFIG_HOME/nvim/init.lua" | so $MYVIMRC'
export HISTFILE="$XDG_DATA_HOME/history"
export KDEHOME="$XDG_CONFIG_HOME/kde"
export KODI_DATA="$XDG_DATA_HOME/kodi"
export MACHINE_STORAGE_PATH="$XDG_DATA_HOME/docker/machine"
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"
export PASSWORD_STORE_DIR="$XDG_DATA_HOME/pass"
export PASSWORD_STORE_CLIP_TIME="15"
export PGPASSFILE="$XDG_CONFIG_HOME/pg/pgpass"
export PGSERVICEFILE="$XDG_CONFIG_HOME/pg/pg_service.conf"
export PSQLRC="$XDG_CONFIG_HOME/pg/psqlrc"
export PSQL_HISTORY="$XDG_STATE_HOME/psql_history"
export PYTHONSTARTUP="$XDG_CONFIG_HOME/python/pythonrc"
export RIPGREP_CONFIG_PATH="$XDG_CONFIG_HOME/ripgrep/config"
export RUSTUP_HOME="$XDG_DATA_HOME/rustup"
export SCREENRC="$XDG_CONFIG_HOME/screen/screenrc"
export SQLITE_HISTORY="$XDG_DATA_HOME/sqlite_history"
export SQLITE_HISTORY="$XDG_DATA_HOME/sqlite_history"
export UNISON="$XDG_DATA_HOME/unison"
export WGETRC="$XDG_CONFIG_HOME/wget/wgetrc"
export WINEPREFIX="$XDG_DATA_HOME/wineprefixes/default"
export XINITRC="$XDG_CONFIG_HOME/x11/xinitrc"
export XSERVERRC="$XDG_CONFIG_HOME/x11/xserverrc"
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="$XDG_CONFIG_HOME/java"

[ ! -f "$XDG_CONFIG_HOME/shell/shortcutrc" ] && setsid -f shortcuts >/dev/null 2>&1

#export QT_QPA_PLATFORMTHEME="gtk2" # Have QT use gtk2 theme.
#export MOZ_USE_XINPUT2="1" # Mozilla smooth scrolling/touchpads.
#export AWT_TOOLKIT="MToolkit wmname LG3D" # May have to install wmname
#export _JAVA_AWT_WM_NONREPARENTING=1 # Fix for Java applications in dwm


[ -d "$ANDROID_HOME" ] && export PATH="$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/cmdline-tools/latest/bin"
[ -d "$GOPATH" ] && export PATH="$PATH:$GOPATH/bin"

## Start graphical server on user's current tty if not already running.
## [ "$(tty)" = "/dev/tty1" ] && ! pidof -s Xorg >/dev/null 2>&1 && exec startx "$XINITRC"
#[ "$(tty)" = "/dev/tty1" ] && ! pidof -s Hyprland >/dev/null 2>&1 && exec Hyprland
#[ -f "$HOME/.config/asound.state" ] && alsactl restore -f ~/.config/asound.state # moved to hyprland autostart config
