set runtimepath^=$XDG_CONFIG_HOME/vim
set runtimepath+=$XDG_DATA_HOME/vim
set runtimepath+=$XDG_CONFIG_HOME/vim/after
set packpath^=$XDG_DATA_HOME/vim,$XDG_CONFIG_HOME/vim
set packpath+=$XDG_CONFIG_HOME/vim/after,$XDG_DATA_HOME/vim/after
let g:netrw_home = $XDG_DATA_HOME."/vim"
call mkdir($XDG_DATA_HOME."/vim/spell", 'p')
set backupdir=$XDG_STATE_HOME/vim/backup | call mkdir(&backupdir, 'p')
set directory=$XDG_STATE_HOME/vim/swap   | call mkdir(&directory, 'p')
set undodir=$XDG_STATE_HOME/vim/undo     | call mkdir(&undodir,   'p')
set viewdir=$XDG_STATE_HOME/vim/view     | call mkdir(&viewdir,   'p')
if !has('nvim') | set viminfofile=$XDG_STATE_HOME/vim/viminfo | endif



map <S-q> <Nop>
syntax on
set ruler
set mouse=a

set tabstop=2
set shiftwidth=2
set scrolloff=10

set undolevels=200

set showmatch
set hlsearch
set incsearch
set ignorecase
set smartcase
set nu
set rnu

set ai

set splitbelow splitright
map <C-h> <C-w>h
map <C-j> <C-w>j
map <C-k> <C-w>k
map <C-l> <C-w>l
"nnoremap <esc> :noh<CR>

" cycle number modes
nnoremap <silent> <F5> :exec &nu==&rnu? "se nu!" : "se rnu!"<cr>
" toggle spellcheck
nnoremap <silent> <F6> :set spell!<CR>

"save read-only file
cabbrev w!! execute 'silent! write !sudo tee % >/dev/null' <bar> edit!

autocmd BufWritePost bm-files,bm-dirs !shortcuts
