-- Hyprland configuration (Lua) — https://wiki.hypr.land/Configuring/Start/
hl.config({ autogenerated = false })

hl.env("QT_QPA_PLATFORM", "wayland;xcb")

hl.on("hyprland.start", function()
	hl.exec_cmd("dbus-update-activation-environment --systemd --all")
	hl.exec_cmd("systemctl --user start hyprland-session.target")
	hl.exec_cmd("sh -c '~/.local/bin/qmk-hid-host -c ~/.config/qmk-hid-host.json >/dev/null'")
end)

hl.config({

	input = {
		kb_layout = "us,ru",
		kb_options = "grp:caps_toggle,grp:win_space_toggle,compose:ralt",
		numlock_by_default = true,
		repeat_delay = 200,
		repeat_rate = 40,
		follow_mouse = 1,
		sensitivity = 0.4,
		accel_profile = "flat",
		touchpad = {
			disable_while_typing = true,
			natural_scroll = true,
			scroll_factor = 0.5,
			tap_to_click = true,
			clickfinger_behavior = true,
			tap_and_drag = true,
		},
	},

	general = {
		-- gaps_in = 2,
		-- gaps_out = 2,
		-- border_size = 2,
		layout = "scrolling",
		resize_on_border = true,
		snap = {
			enabled = true,
		},
	},

	decoration = {
		rounding = 12,
		active_opacity = 1.0,
		inactive_opacity = 1.0,
		shadow = {
			enabled = false,
			range = 30,
			render_power = 5,
			offset = "0 5",
			color = "rgba(00000070)",
		},
	},

	binds = {
		disable_keybind_grabbing = false,
		scroll_event_delay = 0,
	},

	misc = {
		disable_hyprland_logo = true,
		disable_splash_rendering = true,
		key_press_enables_dpms = true,
		focus_on_activate = true,
		anr_missed_pings = 8,
		vrr = 2,
	},

	dwindle = {
		preserve_split = true,
	},

	master = {
		mfact = 0.5,
	},

	scrolling = {
		column_width = 0.667,
		fullscreen_on_one_column = false,
		follow_min_visible = 1,
	},

	ecosystem = {
		enforce_permissions = true,
	},

	cursor = {
		persistent_warps = true,
	},

	render = {
		direct_scanout = 0,
		cm_auto_hdr = 1,
	},
})

hl.permission({ binary = "/usr/bin/grim", type = "screencopy", mode = "allow" })
hl.permission({ binary = "/usr/bin/hyprpicker", type = "screencopy", mode = "allow" })
hl.permission({ binary = "/usr/bin/quickshell", type = "screencopy", mode = "allow" })
hl.permission({ binary = "/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", type = "screencopy", mode = "allow" })
-- hl.permission({ binary = "/usr/(bin|local/bin)/hyprpm", type = "plugin", mode = "allow" })

hl.device({
	name = "tpps/2-ibm-trackpoint",
	sensitivity = 0.15,
	accel_profile = "adaptive",
})

hl.device({
	name = "synps/2-synaptics-touchpad",
	sensitivity = 0.7,
	accel_profile = "adaptive",
})

hl.animation({ leaf = "windowsIn", enabled = true, speed = 2, bezier = "default" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 2, bezier = "default" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 2, bezier = "default" })
hl.animation({ leaf = "windowsMove", enabled = true, speed = 2.5, bezier = "default" })
hl.animation({ leaf = "fade", enabled = true, speed = 2, bezier = "default" })
hl.animation({ leaf = "border", enabled = true, speed = 2, bezier = "default" })

require("dms.colors")
require("dms.outputs")
require("dms.layout")
require("dms.cursor")
require("dms.binds")
require("dms.windowrules")
