-- Generated by gemini https://aistudio.google.com/u/1/prompts/new_chat
-- with this docs: https://raw.githubusercontent.com/mpv-player/mpv/refs/heads/master/DOCS/man/lua.rst

mp = {}

--- Runs the given command.
---@param command string The command to run.
---@return boolean? success True on success, nil on error.
---@return string? error Error message if the command failed.
function mp.command(command) end

--- Runs the given command with variable arguments.
---@vararg string Command arguments.
function mp.commandv(...) end

--- Runs the given command with a table of arguments.
---@param args table Command arguments.
---@param def? any Default value returned on error.
---@return table? result Result table on success.
---@return any? error_def Default value and error message on error.
function mp.command_native(args, def) end

--- Runs the given command asynchronously.
---@param args table Command arguments.
---@param fn fun(success: boolean, result: table?, error: string?): nil Callback function.
---@return table? async_handle Handle to abort the command.
---@return string? error Error message if starting the command failed.
function mp.command_native_async(args, fn) end

--- Aborts an asynchronous command.
---@param handle table The handle returned by `mp.command_native_async`.
function mp.abort_async_command(handle) end

--- Deletes a property.
---@param name string The name of the property to delete.
---@return boolean? success True on success, nil on error.
---@return string? error Error message if the property could not be deleted.
function mp.del_property(name) end

--- Gets the value of a property as a string.
---@param name string The name of the property.
---@param def? any Default value if the property cannot be retrieved.
---@return string? value The property value.
---@return any? error_def Default value and error message on error.
function mp.get_property(name, def) end

--- Gets the value of a property as a string, formatted for OSD.
---@param name string The name of the property.
---@param def? string Default value if the property cannot be retrieved.
---@return string value The property value.
---@return string? error_def Default value and error message on error.
function mp.get_property_osd(name, def) end

--- Gets the value of a property as a boolean.
---@param name string The name of the property.
---@param def? boolean Default value if the property cannot be retrieved.
---@return boolean? value The property value.
---@return any? error_def Default value and error message on error.
function mp.get_property_bool(name, def) end

--- Gets the value of a property as a number.
---@param name string The name of the property.
---@param def? number Default value if the property cannot be retrieved.
---@return number? value The property value.
---@return any? error_def Default value and error message on error.
function mp.get_property_number(name, def) end

--- Gets the value of a property with its native Lua type.
---@param name string The name of the property.
---@param def? any Default value if the property cannot be retrieved.
---@return any value The property value.
---@return any? error_def Default value and error message on error.
function mp.get_property_native(name, def) end

--- Sets the value of a property as a string.
---@param name string The name of the property to set.
---@param value string The value to set.
---@return boolean? success True on success, nil on error.
---@return string? error Error message if the property could not be set.
function mp.set_property(name, value) end

--- Sets the value of a property as a boolean.
---@param name string The name of the property to set.
---@param value boolean The value to set.
function mp.set_property_bool(name, value) end

--- Sets the value of a property as a number.
---@param name string The name of the property to set.
---@param value number The value to set.
function mp.set_property_number(name, value) end

--- Sets the value of a property with its native Lua type.
---@param name string The name of the property to set.
---@param value any The value to set.
function mp.set_property_native(name, value) end

--- Gets the current mpv internal time.
---@return number The current time in seconds.
function mp.get_time() end

--- Adds a key binding.
---@param key string The key to bind (e.g., "Ctrl+a").
---@param name string|fun() Name of the binding or the callback function.
---@param fn? fun(event: table): nil The callback function.
---@param flags? table Additional flags for the binding.
function mp.add_key_binding(key, name, fn, flags) end

--- Adds a forced key binding, overriding user bindings.
---@param key string The key to bind.
---@param name string|fun() Name of the binding or the callback function.
---@param fn? fun(event: table): nil The callback function.
---@param flags? table Additional flags for the binding.
function mp.add_forced_key_binding(key, name, fn, flags) end

--- Removes a key binding.
---@param name string The name of the binding to remove.
function mp.remove_key_binding(name) end

--- Registers a callback for an event.
---@param name string The name of the event.
---@param fn fun(event: table): nil The callback function.
---@return boolean True if the event exists.
function mp.register_event(name, fn) end

--- Unregisters an event callback.
---@param fn fun(event: table): nil The callback function to unregister.
function mp.unregister_event(fn) end

--- Observes a property for changes.
---@param name string The name of the property to observe.
---@param type string? The type of the property ("none", "native", "bool", "string", "number").
---@param fn fun(name: string, value: any): nil The callback function.
function mp.observe_property(name, type, fn) end

--- Unobserves a property.
---@param fn fun(name: string, value: any): nil The callback function to unobserve.
function mp.unobserve_property(fn) end

--- Adds a timeout timer.
---@param seconds number The timeout in seconds.
---@param fn fun(): nil The callback function.
---@param disabled? boolean Whether the timer is initially disabled.
---@return table Timer object.
function mp.add_timeout(seconds, fn, disabled) end

--- Adds a periodic timer.
---@param seconds number The interval in seconds.
---@param fn fun(): nil The callback function.
---@param disabled? boolean Whether the timer is initially disabled.
---@return table Timer object.
function mp.add_periodic_timer(seconds, fn, disabled) end

--- Gets a script option.
---@param key string The name of the option.
---@return string? The option value.
function mp.get_opt(key) end

--- Gets the name of the current script.
---@return string The script name.
function mp.get_script_name() end

--- Gets the directory of the current script.
---@return string? The script directory.
function mp.get_script_directory() end

--- Shows an OSD message.
---@param text string The message to show.
---@param duration? number The duration to show the message for.
function mp.osd_message(text, duration) end

--- Gets the wakeup pipe.
---@return userdata The wakeup pipe.
function mp.get_wakeup_pipe() end

--- Gets the time until the next timer expires.
---@return number? The time until the next timeout.
function mp.get_next_timeout() end

--- Dispatches mpv events.
---@param allow_wait? boolean Whether to block until the next event.
function mp.dispatch_events(allow_wait) end

--- Registers an idle handler.
---@param fn fun(): nil The callback function.
function mp.register_idle(fn) end

--- Unregisters an idle handler.
---@param fn fun(): nil The callback function to unregister.
function mp.unregister_idle(fn) end

--- Enables mpv message output for specific log levels.
---@param level string The minimum log level to receive messages for.
function mp.enable_messages(level) end

--- Registers a handler for script messages.
---@param name string The name of the message to handle.
---@param fn fun(...: any): nil The callback function.
function mp.register_script_message(name, fn) end

--- Unregisters a handler for script messages.
---@param name string The name of the message to unregister.
function mp.unregister_script_message(name) end

--- Creates an OSD overlay.
---@param format string The format of the overlay.
---@return table The OSD overlay object.
function mp.create_osd_overlay(format) end

--- Gets the OSD size.
---@return number width OSD width.
---@return number height OSD height.
---@return number par Pixel aspect ratio.
function mp.get_osd_size() end

--- Exits the current script.
function mp.exit() end

--- Outputs a message to the console.
---@param level string Log level ("fatal", "error", "warn", "info", "v", "debug", "trace").
---@vararg any Message arguments.
function msg.log(level, ...) end

--- Outputs a fatal message to the console.
---@vararg any Message arguments.
function msg.fatal(...) end

--- Outputs an error message to the console.
---@vararg any Message arguments.
function msg.error(...) end

--- Outputs a warning message to the console.
---@vararg any Message arguments.
function msg.warn(...) end

--- Outputs an info message to the console.
---@vararg any Message arguments.
function msg.info(...) end

--- Outputs a verbose message to the console.
---@vararg any Message arguments.
function msg.verbose(...) end

--- Outputs a debug message to the console.
---@vararg any Message arguments.
function msg.debug(...) end

--- Outputs a trace message to the console.
---@vararg any Message arguments.
function msg.trace(...) end

--- Reads script options from config and command line.
---@param table table Default options.
---@param identifier? string Unique identifier for the options.
---@param on_update? fun(list: table<string, boolean>): nil Callback for option updates.
function options.read_options(table, identifier, on_update) end

--- Gets the current working directory.
---@return string? The current working directory.
---@return string? Error message on error.
function utils.getcwd() end

--- Lists directory entries.
---@param path string The path to list.
---@param filter? string Filter for entries ("files", "dirs", "normal", "all").
---@return table? List of directory entries.
---@return string? Error message on error.
function utils.readdir(path, filter) end

--- Gets file information.
---@param path string The path to the file.
---@return table? File information.
---@return string? Error message on error.
function utils.file_info(path) end

--- Splits a path into directory and filename.
---@param path string The path to split.
---@return string The directory part.
---@return string The filename part.
function utils.split_path(path) end

--- Joins two paths.
---@param p1 string The first path part.
---@param p2 string The second path part.
---@return string The joined path.
function utils.join_path(p1, p2) end

--- Runs a subprocess.
---@param t table Subprocess arguments.
---@return table Subprocess result.
function utils.subprocess(t) end

--- Runs a detached subprocess.
---@param t table Subprocess arguments.
function utils.subprocess_detached(t) end

--- Gets the process ID of mpv.
---@return number The process ID.
function utils.getpid() end

--- Gets the environment variables.
---@return table List of environment strings.
function utils.get_env_list() end

--- Parses a JSON string.
---@param str string The JSON string to parse.
---@param trail? boolean Whether to allow trailing data.
---@return any? The parsed JSON value.
---@return string? Error message on error.
---@return string? Trailing data if `trail` is true.
function utils.parse_json(str, trail) end

--- Formats a value as a JSON string.
---@param v any The value to format.
---@return string? The JSON string.
---@return string? Error message on error.
function utils.format_json(v) end

--- Converts a value to a string.
---@param v any The value to convert.
---@return string The string representation.
function utils.to_string(v) end

--- Shows the input console.
---@param table table Input configuration.
function input.get(table) end

--- Closes the input console.
function input.terminate() end

--- Logs a message to the input console.
---@param message string The message to log.
---@param style? string ASS tags for styling.
---@param terminal_style? string Terminal escape sequences for styling.
function input.log(message, style, terminal_style) end

--- Logs an error message to the input console.
---@param message string The error message to log.
function input.log_error(message) end

--- Sets the entire log buffer of the input console.
---@param log table List of log entries.
function input.set_log(log) end

--- Shows a selection list in the input console.
---@param table table Selection configuration.
function input.select(table) end

--- Adds a hook callback.
---@param type string The type of hook.
---@param priority number The priority of the hook.
---@param fn fun(hook: table): nil The callback function.
function mp.add_hook(type, priority, fn) end

return mp
