#https://wiki.hypr.land/Configuring/Monitors/

# PC
monitorv2 {
	output = DP-3
	mode = 3840x2160@60
	position = 0x0
	vrr = 2
	bitdepth = 10
	sdrsaturation = 1.0
	sdrbrightness = 1.0
}

render {
	cm_fs_passthrough=2 # Fullscreen HDR without hdr cm setting
}

# Laptop
monitor=eDP-1,2560x1600@60, 0x0, 1
monitor=Unknown-1,disabled

# Others
monitor=, preferred, auto, 1
monitor=HDMI-A-1, 1920x1080, 960x2160,1
