# https://wiki.hypr.land/Configuring/Window-Rules/

windowrule = match:initial_title Mozilla Firefox, workspace 1 silent

windowrule = match:class org.telegram.desktop, workspace 4 silent, no_screen_share true
windowrule = match:class discord, workspace 4 silent

windowrule = match:class steam, workspace 5 silent
windowrule = match:initial_title ^(Friends List)$, float true
windowrule = match:initial_title Steam Settings, float true

windowrule = match:class polkit-gnome-authentication-agent-1, stay_focused true, no_screen_share true
windowrule = match:class Pinentry-gtk-2, stay_focused true, no_screen_share true
windowrule = match:class gcr-prompter, stay_focused true, no_screen_share true

windowrule = fullscreen true, match:class org.telegram.desktop,match:title Media viewer, no_screen_share false

windowrule = float true, match:class blobdrop
windowrule = pin true, match:class blobdrop

windowrule = float true, match:title (.*Calculator.*)
windowrule = float true, match:title (.*calculator.*)
windowrule = float true, match:title (.*Launcher.*)
windowrule = float true, match:title (.*launcher.*)
windowrule = float true, match:initial_class (Zenity)
windowrule = float true, match:initial_class (zenity)
windowrule = float true, match:class (org.pulseaudio.pavucontrol)
windowrule = float true, match:class (blueman-manager)
windowrule = float true, match:class (org.prismlauncher.PrismLauncher)
windowrule = float true, match:class (org.kde.kdeconnect.daemon)
windowrule = float true, match:class (it.mijorus.smile)
windowrule = size 100 100, match:class (it.mijorus.smile)

windowrule = float true, match:class (xdg-desktop-portal-gtk)
windowrule = size 1600 1100, match:class (xdg-desktop-portal-gtk)

windowrule = float true, match:class (com.usebottles.bottles)
windowrule = size 1000 900, match:class (com.usebottles.bottles)

windowrule = float true, match:class (floating)
windowrule = size 1200 900, match:class (floating)
windowrule = center true, match:class (floating)

windowrule {
	name = firefox_pip
	match:class = org.mozilla.firefox
	match:title = Picture-in-Picture
	float = true
	pin = true
	move = 10 50
}

windowrule {
  name = ueberzugpp
  match:class = ^(ueberzugpp.*)$
  float = true
  no_anim = true
  border_size = 0
  no_focus = true
  no_follow_mouse = true
  no_blur = true
}

windowrule = float true, match:workspace 6
windowrule = float true, match:workspace 7
windowrule = float true, match:workspace 8
windowrule = float true, match:workspace 9
windowrule = float true, match:workspace 10


# ## part of smartgaps (https://wiki.hypr.land/Configuring/Workspace-Rules/#smart-gaps)
# windowrule = border_size 0, match:float 0, match:workspace w[tv1]
# windowrule = rounding 0, match:float 0, match:workspace w[tv1]
# windowrule = border_size 0, match:float 0, match:workspace f[1]
# windowrule = rounding 0, match:float 0, match:workspace f[1]

layerrule = match:namespace wofi, no_anim true, no_screen_share true
layerrule = match:namespace swaync-notification-window, no_screen_share true
layerrule = match:namespace swaync-control-center, no_screen_share true
