-- Auto-generated by DMS — do not edit manually

hl.monitor({
	output = "DP-3",
	mode = "3840x2160@59.997",
	position = "0x0",
	scale = 1,
	vrr = 2,
	bitdepth = 10,
})

hl.monitor({
	output = "eDP-1",
	mode = "2560x1600@60",
	position = "0x0",
	scale = 1,
})

hl.monitor({
	output = "Unknown-1",
	disabled = true,
})

hl.monitor({
	output = "",
	mode = "preferred",
	position = "0x0",
	scale = 1,
})

